import 'package:hive/hive.dart';

part 'app_scheme.g.dart';

@HiveType(typeId: 17)
enum AppScheme {
  @HiveField(0)
  material,
  @HiveField(1)
  materialHc,
  @HiveField(2)
  blue,
  @HiveField(3)
  indigo,
  @HiveField(4)
  hippieBlue,
  @HiveField(5)
  aquaBlue,
  @HiveField(6)
  brandBlue,
  @HiveField(7)
  deepBlue,
  @HiveField(8)
  sakura,
  @HiveField(9)
  mandyRed,
  @HiveField(10)
  red,
  @HiveField(11)
  redWine,
  @HiveField(12)
  purpleBrown,
  @HiveField(13)
  green,
  @HiveField(14)
  money,
  @HiveField(15)
  jungle,
  @HiveField(16)
  greyLaw,
  @HiveField(17)
  wasabi,
  @HiveField(18)
  gold,
  @HiveField(19)
  mango,
  @HiveField(20)
  amber,
  @HiveField(21)
  vesuviusBurn,
  @HiveField(22)
  deepPurple,
  @HiveField(23)
  ebonyClay,
  @HiveField(24)
  barossa,
  @HiveField(25)
  shark,
  @HiveField(26)
  bigStone,
  @HiveField(27)
  damask,
  @HiveField(28)
  bahamaBlue,
  @HiveField(29)
  mallardGreen,
  @HiveField(30)
  espresso,
  @HiveField(31)
  outerSpace,
  @HiveField(32)
  blueWhale,
  @HiveField(33)
  sanJuanBlue,
  @HiveField(34)
  rosewood,
  @HiveField(35)
  blumineBlue,
  @HiveField(36)
  flutterDash,
  @HiveField(37)
  materialBaseline,
  @HiveField(38)
  verdunHemlock,
  @HiveField(39)
  dellGenoa,
  @HiveField(40)
  redM3,
  @HiveField(41)
  pinkM3,
  @HiveField(42)
  purpleM3,
  @HiveField(43)
  indigoM3,
  @HiveField(44)
  blueM3,
  @HiveField(45)
  cyanM3,
  @HiveField(46)
  tealM3,
  @HiveField(47)
  greenM3,
  @HiveField(48)
  limeM3,
  @HiveField(49)
  yellowM3,
  @HiveField(50)
  orangeM3,
  @HiveField(51)
  deepOrangeM3,
  @HiveField(52)
  blackWhite,
  @HiveField(53)
  greys,
  @HiveField(54)
  sepia,
  @HiveField(55)
  shadBlue,
  @HiveField(56)
  shadGray,
  @HiveField(57)
  shadGreen,
  @HiveField(58)
  shadNeutral,
  @HiveField(59)
  shadOrange,
  @HiveField(60)
  shadRed,
  @HiveField(61)
  shadRose,
  @HiveField(62)
  shadSlate,
  @HiveField(63)
  shadStone,
  @HiveField(64)
  shadViolet,
  @HiveField(65)
  shadYellow,
  @HiveField(66)
  shadZinc,
}
